/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BO.IngresoProductoBO;
import DATABASE.Conexion;
import ENTITY.IngresoProducto;
import javax.swing.JOptionPane;

/**
 *
 * @author BRIAN
 */
public class INGRESO extends javax.swing.JFrame {
    private Conexion con = new Conexion();
    private IngresoProductoBO IPBO = new IngresoProductoBO();
    /**
     * Creates new form INGRESO
     */
    public INGRESO() {
        initComponents();
        this.cmbPaisIP.setModel(con.obt_Pais());
        this.cmbTipoIP.setModel(con.obt_Tipo());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVaciarIP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        txtContridpiIP = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        txtPreUnitIP = new javax.swing.JTextField();
        txtCantIP = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        txtFechaIngIP = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        cmbTipoIP = new javax.swing.JComboBox<String>();
        label11 = new java.awt.Label();
        cmbPaisIP = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtCodigoIP = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        txtIvaUnitIP = new javax.swing.JTextField();
        txtCostoImpIP = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        txtDescIP = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        txtUsuarioIP = new javax.swing.JTextField();
        btnGuardarIP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/enviar (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 130, -1));

        jLabel2.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INGRESO PRODUCTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/deshacer.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 70, 70));

        btnVaciarIP.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        btnVaciarIP.setText("VACIAR");
        btnVaciarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarIPActionPerformed(evt);
            }
        });
        getContentPane().add(btnVaciarIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 220, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label6.setText("TIPO");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 50, 30));

        label7.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label7.setText("FECHA INGRESO");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));
        jPanel2.add(txtContridpiIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 270, 30));

        label8.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label8.setText("CONTRIBUYENTE DPI");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        txtPreUnitIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreUnitIPActionPerformed(evt);
            }
        });
        jPanel2.add(txtPreUnitIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 270, 30));

        txtCantIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantIPActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 270, 30));

        label9.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label9.setText("CANTIDAD");
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, 30));
        jPanel2.add(txtFechaIngIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 270, 30));

        label10.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label10.setText("PRECIO UNIT");
        jPanel2.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        jPanel2.add(cmbTipoIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 140, 30));

        label11.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label11.setText("PAIS ");
        jPanel2.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 50, 30));

        jPanel2.add(cmbPaisIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 960, 140));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label1.setText("USUARIO ");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 90, 30));

        label2.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label2.setText("DESCRIPCIÓN");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));
        jPanel1.add(txtCodigoIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 270, 30));

        label3.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label3.setText("CODIGO");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        txtIvaUnitIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaUnitIPActionPerformed(evt);
            }
        });
        jPanel1.add(txtIvaUnitIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 270, 30));

        txtCostoImpIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoImpIPActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoImpIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 240, 30));

        label4.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label4.setText("COSTO IMPORT*");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 160, 30));
        jPanel1.add(txtDescIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 270, 30));

        label5.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        label5.setText("IVA UNIT");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        txtUsuarioIP.setEnabled(false);
        txtUsuarioIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioIPActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarioIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 960, 140));

        btnGuardarIP.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 18)); // NOI18N
        btnGuardarIP.setText("GUARDAR");
        btnGuardarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIPActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 220, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/thumb-1920-429165 (2).jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIvaUnitIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaUnitIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaUnitIPActionPerformed

    private void txtCostoImpIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoImpIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoImpIPActionPerformed

    private void txtUsuarioIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioIPActionPerformed

    private void txtPreUnitIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreUnitIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreUnitIPActionPerformed

    private void txtCantIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantIPActionPerformed

    private void btnVaciarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarIPActionPerformed
        this.txtCantIP.setText("");
        this.txtCodigoIP.setText("");
        this.txtContridpiIP.setText("");
        this.txtCostoImpIP.setText("");
        this.txtDescIP.setText("");
        this.txtFechaIngIP.setText("");
        this.txtIvaUnitIP.setText("");
        this.txtPreUnitIP.setText("");
        this.txtUsuarioIP.setText("");
    }//GEN-LAST:event_btnVaciarIPActionPerformed

    private void btnGuardarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIPActionPerformed
        if(this.txtCantIP.getText().isEmpty() || this.txtCodigoIP.getText().isEmpty() || this.txtContridpiIP.getText().isEmpty() || this.txtCostoImpIP.getText().isEmpty()
                || this.txtDescIP.getText().isEmpty() || this.txtFechaIngIP.getText().isEmpty() || this.txtIvaUnitIP.getText().isEmpty() || this.txtPreUnitIP.getText().isEmpty()
                || this.txtUsuarioIP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
        }else{
            IngresoProducto ip = new IngresoProducto();
            ip.setDescripcion(this.txtDescIP.getText());
            ip.setPrecioUnitario(Double.parseDouble(this.txtPreUnitIP.getText()));
            ip.setCantidadArt(Integer.parseInt(this.txtCantIP.getText()));
            ip.setIvaTotal(Double.parseDouble(this.txtIvaUnitIP.getText()));
            ip.setImporteTotal(Double.parseDouble(this.txtCostoImpIP.getText()));
            ip.setRiesgoProducto(this.cmbTipoIP.getSelectedIndex());
            ip.setId_DPI(Integer.parseInt(this.txtContridpiIP.getText()));
            ip.setId_PAIS(this.cmbPaisIP.getSelectedIndex());
            ip.setId_TIPO(this.cmbTipoIP.getSelectedIndex());
            
            
        }
    }//GEN-LAST:event_btnGuardarIPActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        ESTADOS  I=new ESTADOS();
        I.show();
        dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INGRESO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarIP;
    private javax.swing.JButton btnVaciarIP;
    private javax.swing.JComboBox<String> cmbPaisIP;
    private javax.swing.JComboBox<String> cmbTipoIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField txtCantIP;
    private javax.swing.JTextField txtCodigoIP;
    private javax.swing.JTextField txtContridpiIP;
    private javax.swing.JTextField txtCostoImpIP;
    private javax.swing.JTextField txtDescIP;
    private javax.swing.JTextField txtFechaIngIP;
    private javax.swing.JTextField txtIvaUnitIP;
    private javax.swing.JTextField txtPreUnitIP;
    private javax.swing.JTextField txtUsuarioIP;
    // End of variables declaration//GEN-END:variables
}
